language: go
go_import_path: github.com/kubernetes-sigs/azurefile-csi-driver
dist: bionic

env:
  global:
    - GO111MODULE=on

go:
  - "1.12.1"

jobs:
  include:
    - stage: test
      name: "build test"
      install:
        - GO111MODULE=off go get github.com/mattn/goveralls
      script:
        - make azurefile
        - make azurefile-container
        - make azurefile-windows
        - go test -covermode=count -coverprofile=profile.cov ./pkg/...
    - stage: test
      name: "code verification test"
      script:
        - make verify-modules      
        - hack/verify-all.sh
    - stage: test
      name: "sanity test"
      install:
        - sudo apt update && sudo apt install cifs-utils procps -y
      script: make sanity-test
      # after_failure: TRAVIS_TEST_RESULT=0
    - stage: test
      name: "integration test"
      install:
        - GO111MODULE=off go get github.com/rexray/gocsi/csc
        - sudo apt update && sudo apt install cifs-utils procps -y
      script:
        - make azurefile
        - make integration-test
    - stage: test
      name: "e2e test"
      install:
        - GO111MODULE=off go get github.com/kubernetes/kubernetes/cmd/kubectl
      script:
        - make e2e-test
